import type { APIRoute } from 'astro';
import { NodeHtmlMarkdown } from 'node-html-markdown-cloudflare'

function cleanMarkdown(markdown: string): string {
  return markdown
    // Remove excessive blank lines (more than 2)
    .replace(/\n{3,}/g, '\n\n')
    // Remove leading/trailing whitespace from lines
    .split('\n')
    .map((line) => line.trimEnd())
    .join('\n')
    // Trim the whole document
    .trim();
}

// Process HTML to Markdown
async function processHtmlToMarkdown(html: string, pageUrl: URL): Promise<string> {
    let contentHtml = html;

    // Try to extract main content
    const mainMatch = html.match(/<main[^>]*>([\s\S]*?)<\/main>/i);
    if (mainMatch) {
        contentHtml = mainMatch[1];
    } else {
        // Fallback: try to extract body content without header/footer/nav
        const bodyMatch = html.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
        if (bodyMatch) {
        contentHtml = bodyMatch[1];
        }
    }

  
    const nhm = new NodeHtmlMarkdown();
    let markdown = nhm.translate(contentHtml);
    // Clean up the markdown
    markdown = cleanMarkdown(markdown);

    // Build final markdown content
    let finalMarkdown = '<!-- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT! -->\n\n';

    finalMarkdown += markdown;

    // Add metadata section at the end
    finalMarkdown += '\n\n---\n\n';
    finalMarkdown += `## Page Metadata\n\n`;
    finalMarkdown += `- **URL**: ${pageUrl.toString()}\n`;
    finalMarkdown += `- **Generated**: ${new Date().toISOString()}\n`;

    return finalMarkdown;
}

export const GET: APIRoute = async ({ params, url, request }) => {
  try {
    const slugPath = params.slug || '';
    const pageUrl = new URL(`/blog/${slugPath}`, url.origin);
    
    const fetchOptions: RequestInit & { dispatcher?: unknown } = {
      headers: {
        'User-Agent': request.headers.get('User-Agent') || 'Mozilla/5.0',
        Accept: 'text/html',
      },
    };

    const htmlResponse = await fetch(pageUrl.toString(), fetchOptions);

    if (!htmlResponse.ok) {
      return new Response(`Page not found: ${pageUrl.toString()}`, {
        status: htmlResponse.status,
        headers: {
          'Content-Type': 'text/plain',
        },
      });
    }

    const html = await htmlResponse.text();
    const markdown = await processHtmlToMarkdown(html, pageUrl);

    return new Response(markdown, {
        status: 200,
        headers: {
          'Content-Type': 'text/markdown; charset=utf-8',
        },
      });
  } catch (error) {
    console.error('Error generating markdown:', error);

    return new Response(`Error generating markdown: ${error instanceof Error ? error.message : 'Unknown error'}`, {
      status: 500,
      headers: {
        'Content-Type': 'text/plain',
      },
    });
  }
};
