// Auto-generated Storyblok component types
// Do not edit this file manually - it will be overwritten
// Generated on: 2025-09-30T15:03:48.514Z
// Total components: 44

// Base Storyblok types

/**
 * Common value types used in Storyblok
 */
export type StoryblokPrimitiveValue = string | number | boolean | null;
export type StoryblokMetadataValue = StoryblokPrimitiveValue | StoryblokPrimitiveValue[] | Record<string, StoryblokPrimitiveValue>;

/**
 * Storyblok rich text node attributes
 */
export interface StoryblokRichtextAttrs {
  /** Text alignment */
  textAlign?: 'left' | 'center' | 'right' | 'justify';
  /** Link URL (for link nodes) */
  href?: string;
  /** Link target */
  target?: '_blank' | '_self' | '_parent' | '_top';
  /** HTML class names */
  class?: string;
  /** Anchor ID */
  id?: string;
  /** Text color */
  color?: string;
  /** Background color */
  backgroundColor?: string;
  /** Font size */
  fontSize?: string;
  /** Custom attributes */
  [key: string]: StoryblokPrimitiveValue;
}

/**
 * Storyblok rich text mark attributes
 */
export interface StoryblokRichtextMarkAttrs {
  /** Link URL (for link marks) */
  href?: string;
  /** Link target */
  target?: '_blank' | '_self' | '_parent' | '_top';
  /** Text color */
  color?: string;
  /** Custom attributes */
  [key: string]: StoryblokPrimitiveValue;
}

/**
 * Storyblok asset (image, video, document, etc.)
 */
export interface StoryblokAsset {
  /** Asset ID */
  id?: number;
  /** Asset filename/URL */
  filename: string;
  /** Alt text for accessibility */
  alt?: string;
  /** Asset name */
  name?: string;
  /** Focus point for cropping (e.g., "100x100:200x200") */
  focus?: string;
  /** Asset title */
  title?: string;
  /** Copyright information */
  copyright?: string;
  /** Asset metadata */
  meta_data?: Record<string, StoryblokMetadataValue>;
}

/**
 * Storyblok link field (internal links, external URLs, etc.)
 */
export interface StoryblokLink {
  /** Link ID */
  id?: string;
  /** Link URL */
  url?: string;
  /** Type of link */
  linktype?: 'story' | 'asset' | 'url' | 'email';
  /** Field type identifier */
  fieldtype?: string;
  /** Cached URL for internal links */
  cached_url?: string;
  /** Linked story information (for internal links) */
  story?: {
    id: number;
    uuid: string;
    name: string;
    slug: string;
    full_slug: string;
    url: string;
  };
}

/**
 * Storyblok rich text content (structured text with formatting)
 */
export interface StoryblokRichtext {
  /** Node type (e.g., 'doc', 'paragraph', 'text') */
  type: string;
  /** Child nodes */
  content?: StoryblokRichtext[];
  /** Text formatting marks */
  marks?: Array<{
    type: string;
    attrs?: StoryblokRichtextMarkAttrs;
  }>;
  /** Node attributes */
  attrs?: StoryblokRichtextAttrs;
  /** Text content (for text nodes) */
  text?: string;
}

/**
 * Storyblok table field
 */
export interface StoryblokTable {
  /** Table header */
  thead: Array<{
    _uid: string;
    value: string;
  }>;
  /** Table body */
  tbody: Array<{
    _uid: string;
    body: Array<{
      _uid: string;
      value: string;
    }>;
  }>;
}

// Utility types

/**
 * Extract component type from a Storyblok component
 */
export type StoryblokComponentType<T> = T extends { component: infer C } ? C : never;

/**
 * Filter components by type
 */
export type StoryblokComponentByType<T, K extends string> = T extends { component: K } ? T : never;

/**
 * Make all properties of a Storyblok component optional (useful for partial updates)
 */
export type PartialStoryblokComponent<T> = Partial<Omit<T, '_uid' | 'component'>> & Pick<T, '_uid' | 'component'>;

// Datasource-based types

/**
 * Options for spacing datasource
 */
export type Spacing = 'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl';

// Layout Components

/**
 * Storyblok component: CtaSection
 */
export interface CtaSectionStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "CtaSection";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: bloks */
  ctaLink: Array<LinkStoryblok>;
  title?: string;
}

/**
 * Storyblok component: NavSection
 */
export interface NavSectionStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "NavSection";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: bloks */
  links?: Array<LinkStoryblok>;
  name?: string;
}

/**
 * Storyblok component: Page
 */
export interface PageStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "Page";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: bloks */
  body?: StoryblokComponent[];
  /** Field type: textarea */
  description?: string;
  /** Field type: asset */
  image?: StoryblokAsset;
  title?: string;
}

// Content Components

/**
 * Storyblok component: ContentCentered
 */
export interface ContentCenteredStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "ContentCentered";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: richtext */
  body?: StoryblokRichtext;
  description?: string;
  subtitle?: string;
  title?: string;
}

/**
 * Storyblok component: RichTextContent
 */
export interface RichTextContentStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "RichTextContent";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: richtext */
  text?: StoryblokRichtext;
}

/**
 * Storyblok component: Text
 */
export interface TextStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "Text";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  text?: string;
}

// Ui Components

/**
 * Storyblok component: ArticleCard
 */
export interface ArticleCardStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "ArticleCard";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: option */
  post?: StoryblokStory<PostStoryblok> | string;
}

/**
 * Storyblok component: ImageCardWithAuthor
 */
export interface ImageCardWithAuthorStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "ImageCardWithAuthor";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: option */
  author?: StoryblokStory<AuthorStoryblok> | string;
  description?: string;
  /** Field type: asset */
  image?: StoryblokAsset;
  /** Field type: multilink */
  postLink?: StoryblokLink;
  subtitle?: string;
  title?: string;
}

/**
 * Storyblok component: Link
 */
export interface LinkStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "Link";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: multilink */
  link: StoryblokLink;
  name?: string;
}

/**
 * Storyblok component: LinksColumn
 */
export interface LinksColumnStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "LinksColumn";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: bloks */
  links?: Array<LinkStoryblok>;
  title?: string;
}

/**
 * Storyblok component: OffsetIconCard
 */
export interface OffsetIconCardStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "OffsetIconCard";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  description?: string;
  /** Field type: asset */
  icon?: StoryblokAsset;
  title?: string;
}

/**
 * Storyblok component: RoundedAvatarCard
 */
export interface RoundedAvatarCardStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "RoundedAvatarCard";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  description?: string;
  /** Field type: asset */
  image?: StoryblokAsset;
  title?: string;
}

/**
 * Storyblok component: ThreeColumnCards
 */
export interface ThreeColumnCardsStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "ThreeColumnCards";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: bloks */
  cards?: Array<ImageCardWithAuthorStoryblok | ArticleCardStoryblok>;
  description?: string;
  title?: string;
}

/**
 * Storyblok component: TwoGridColumnCard
 */
export interface TwoGridColumnCardStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "TwoGridColumnCard";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: asset */
  asset?: StoryblokAsset;
  description?: string;
  title?: string;
}

// Form Components

/**
 * Storyblok component: HeroWithInputAndAsset
 */
export interface HeroWithInputAndAssetStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "HeroWithInputAndAsset";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: asset */
  asset?: StoryblokAsset;
  description?: string;
  subtitle?: string;
  title?: string;
}

/**
 * Storyblok component: InputRow
 */
export interface InputRowStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "InputRow";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  buttonText?: string;
  smallText?: string;
  title?: string;
}

// Media Components

/**
 * Storyblok component: GridWithRoundImages
 */
export interface GridWithRoundImagesStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "GridWithRoundImages";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: bloks */
  avatarCards?: Array<RoundedAvatarCardStoryblok>;
  description?: string;
  title?: string;
}

/**
 * Storyblok component: HeroWithAngledImage
 */
export interface HeroWithAngledImageStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "HeroWithAngledImage";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  bottomHeader?: string;
  description?: string;
  /** Field type: asset */
  image?: StoryblokAsset;
  /** Field type: bloks */
  links?: Array<LinkStoryblok>;
  topHeader?: string;
}

/**
 * Storyblok component: Image
 */
export interface ImageStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "Image";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: asset */
  image?: StoryblokAsset;
}

/**
 * Storyblok component: PanelWithImage
 */
export interface PanelWithImageStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "PanelWithImage";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  bottomHeader?: string;
  description?: string;
  /** Field type: asset */
  image?: StoryblokAsset;
  /** Field type: bloks */
  link?: Array<LinkStoryblok>;
  topHeader?: string;
}

/**
 * Storyblok component: PanelWithOverlapImage
 */
export interface PanelWithOverlapImageStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "PanelWithOverlapImage";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  description?: string;
  /** Field type: asset */
  image?: StoryblokAsset;
  /** Field type: bloks */
  link?: Array<LinkStoryblok>;
  title?: string;
}

// Other Components

/**
 * Storyblok component: AccordionCentered
 */
export interface AccordionCenteredStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "AccordionCentered";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: bloks */
  faqRows?: Array<FaqRowStoryblok>;
  title?: string;
}

/**
 * Storyblok component: Animation
 */
export interface AnimationStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "Animation";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: asset */
  asset?: StoryblokAsset;
}

/**
 * Storyblok component: Author
 */
export interface AuthorStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "Author";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: asset */
  image?: StoryblokAsset;
  name?: string;
}

/**
 * Storyblok component: Category
 */
export interface CategoryStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "Category";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  description?: string;
  name?: string;
}

/**
 * Storyblok component: ContactCentered
 */
export interface ContactCenteredStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "ContactCentered";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  buttonText?: string;
  companyLabel?: string;
  description?: string;
  emailLabel?: string;
  firstNameLabel?: string;
  lastNameLabel?: string;
  messageLabel?: string;
  phoneNumberLabel?: string;
  title?: string;
  /** Field type: richtext */
  toggleText?: StoryblokRichtext;
}

/**
 * Storyblok component: FaqRow
 */
export interface FaqRowStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "FaqRow";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  answer?: string;
  question?: string;
}

/**
 * Storyblok component: FeatureGrid
 */
export interface FeatureGridStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "FeatureGrid";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  description?: string;
  /** The features displayed in the grid (bloks) */
  features?: Array<FeatureGridItemStoryblok>;
  headline?: string;
  /** Field type: option */
  spacingBottom?: Spacing;
  /** Field type: option */
  spacingTop?: Spacing;
  tagline?: string;
}

/**
 * Storyblok component: FeatureGridItem
 */
export interface FeatureGridItemStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "FeatureGridItem";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: richtext */
  description?: StoryblokRichtext;
  /** Field type: option */
  icon: "CloudUpload" | "Cog" | "LockClosed" | "Refresh" | "Server" | "ShieldCheck";
  title?: string;
}

/**
 * Storyblok component: FeedbackSimple
 */
export interface FeedbackSimpleStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "FeedbackSimple";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  description?: string;
  /** Field type: bloks */
  links?: Array<LinkStoryblok>;
  status?: string;
  title?: string;
}

/**
 * Storyblok component: Footer
 */
export interface FooterStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "Footer";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  copyrightText?: string;
  description?: string;
  /** Field type: bloks */
  icons?: Array<LogoCloudStoryblok>;
  /** Field type: bloks */
  linkColumns?: Array<LinksColumnStoryblok>;
  /** Field type: asset */
  logo?: StoryblokAsset;
}

/**
 * Storyblok component: GlobalSettings
 */
export interface GlobalSettingsStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "GlobalSettings";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: bloks */
  bottomLinks?: Array<LinkStoryblok>;
  /** Field type: bloks */
  footerSections?: Array<NavSectionStoryblok>;
  /** Field type: asset */
  illustration?: StoryblokAsset;
  /** Field type: bloks */
  navItems?: Array<NavSectionStoryblok | LinkStoryblok>;
  /** Field type: bloks */
  redirects?: Array<RedirectItemStoryblok>;
}

/**
 * Storyblok component: GridWithOffsetIcons
 */
export interface GridWithOffsetIconsStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "GridWithOffsetIcons";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  description?: string;
  /** Field type: bloks */
  iconCards?: StoryblokComponent[];
  subtitle?: string;
  title?: string;
}

/**
 * Storyblok component: HelloWorld
 */
export interface HelloWorldStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "HelloWorld";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  name?: string;
}

/**
 * Storyblok component: Hero
 */
export interface HeroStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "Hero";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: bloks */
  ctaLink?: Array<LinkStoryblok>;
  description?: string;
  headingBlack?: string;
  headingColorful?: string;
  /** Field type: asset */
  image?: StoryblokAsset;
}

/**
 * Storyblok component: LatestPosts
 */
export interface LatestPostsStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "LatestPosts";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Optionally restrict the latest posts to a certain category. (option) */
  category?: StoryblokStory<CategoryStoryblok> | string;
  title?: string;
}

/**
 * Storyblok component: LogoCloud
 */
export interface LogoCloudStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "LogoCloud";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: multiasset */
  logo?: StoryblokAsset[];
  /** Field type: option */
  spacingBottom?: Spacing;
  /** Field type: option */
  spacingTop?: Spacing;
}

/**
 * Storyblok component: Office
 */
export interface OfficeStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "Office";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: bloks */
  body?: Array<TextStoryblok | RichTextContentStoryblok>;
  title?: string;
}

/**
 * Storyblok component: OffsetTwoRowGrid
 */
export interface OffsetTwoRowGridStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "OffsetTwoRowGrid";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: bloks */
  cards?: Array<TwoGridColumnCardStoryblok>;
  header?: string;
}

/**
 * Storyblok component: Post
 */
export interface PostStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "Post";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: option */
  author?: StoryblokStory<AuthorStoryblok> | string;
  /** Field type: bloks */
  body?: Array<HelloWorldStoryblok | RichTextContentStoryblok>;
  /** Field type: options */
  categories?: Array<StoryblokStory<CategoryStoryblok> | string>;
  /** Field type: asset */
  image?: StoryblokAsset;
  /** Field type: textarea */
  intro?: string;
  title: string;
  /** Field type: option */
  type?: "article" | "video" | "case-study";
}

/**
 * Storyblok component: RedirectItem
 */
export interface RedirectItemStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "RedirectItem";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** The url path you will redirect. e.g. /hello/there */
  from?: string;
  /** Field type: boolean */
  permanent?: boolean;
  /** Where to redirect. An absolute path or a full url.
e.g. /about, https://example.org or https://example.org/hello */
  to?: string;
}

/**
 * Storyblok component: SimpleCenterBranded
 */
export interface SimpleCenterBrandedStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "SimpleCenterBranded";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  bottomHeader?: string;
  description?: string;
  /** Field type: bloks */
  link?: Array<LinkStoryblok>;
  topHeader?: string;
}

/**
 * Storyblok component: SimpleCenteredHeader
 */
export interface SimpleCenteredHeaderStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "SimpleCenteredHeader";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  /** Field type: richtext */
  description?: StoryblokRichtext;
  /** Field type: option */
  spacingBottom?: Spacing;
  /** Field type: option */
  spacingTop?: Spacing;
  subTitle?: string;
  title?: string;
}

/**
 * Storyblok component: SimpleFourColumn
 */
export interface SimpleFourColumnStoryblok {
  /** Unique identifier for the component instance */
  _uid: string;
  /** Component type identifier */
  component: "SimpleFourColumn";
  /** Visual editor inline HTML for editing */
  _editable?: string;
  description?: string;
  /** Field type: bloks */
  offices?: Array<OfficeStoryblok>;
  title?: string;
}

/** Union type for layout components */
export type StoryblokLayoutComponent = CtaSectionStoryblok | NavSectionStoryblok | PageStoryblok;

/** Union type for content components */
export type StoryblokContentComponent = ContentCenteredStoryblok | RichTextContentStoryblok | TextStoryblok;

/** Union type for ui components */
export type StoryblokUiComponent = ArticleCardStoryblok | ImageCardWithAuthorStoryblok | LinkStoryblok | LinksColumnStoryblok | OffsetIconCardStoryblok | RoundedAvatarCardStoryblok | ThreeColumnCardsStoryblok | TwoGridColumnCardStoryblok;

/** Union type for form components */
export type StoryblokFormComponent = HeroWithInputAndAssetStoryblok | InputRowStoryblok;

/** Union type for media components */
export type StoryblokMediaComponent = GridWithRoundImagesStoryblok | HeroWithAngledImageStoryblok | ImageStoryblok | PanelWithImageStoryblok | PanelWithOverlapImageStoryblok;

/** Union type for other components */
export type StoryblokOtherComponent = AccordionCenteredStoryblok | AnimationStoryblok | AuthorStoryblok | CategoryStoryblok | ContactCenteredStoryblok | FaqRowStoryblok | FeatureGridStoryblok | FeatureGridItemStoryblok | FeedbackSimpleStoryblok | FooterStoryblok | GlobalSettingsStoryblok | GridWithOffsetIconsStoryblok | HelloWorldStoryblok | HeroStoryblok | LatestPostsStoryblok | LogoCloudStoryblok | OfficeStoryblok | OffsetTwoRowGridStoryblok | PostStoryblok | RedirectItemStoryblok | SimpleCenterBrandedStoryblok | SimpleCenteredHeaderStoryblok | SimpleFourColumnStoryblok;

/** Union type of all Storyblok components */
export type StoryblokComponent = AccordionCenteredStoryblok | AnimationStoryblok | ArticleCardStoryblok | AuthorStoryblok | CategoryStoryblok | ContactCenteredStoryblok | ContentCenteredStoryblok | CtaSectionStoryblok | FaqRowStoryblok | FeatureGridStoryblok | FeatureGridItemStoryblok | FeedbackSimpleStoryblok | FooterStoryblok | GlobalSettingsStoryblok | GridWithOffsetIconsStoryblok | GridWithRoundImagesStoryblok | HelloWorldStoryblok | HeroStoryblok | HeroWithAngledImageStoryblok | HeroWithInputAndAssetStoryblok | ImageStoryblok | ImageCardWithAuthorStoryblok | InputRowStoryblok | LatestPostsStoryblok | LinkStoryblok | LinksColumnStoryblok | LogoCloudStoryblok | NavSectionStoryblok | OfficeStoryblok | OffsetIconCardStoryblok | OffsetTwoRowGridStoryblok | PageStoryblok | PanelWithImageStoryblok | PanelWithOverlapImageStoryblok | PostStoryblok | RedirectItemStoryblok | RichTextContentStoryblok | RoundedAvatarCardStoryblok | SimpleCenterBrandedStoryblok | SimpleCenteredHeaderStoryblok | SimpleFourColumnStoryblok | TextStoryblok | ThreeColumnCardsStoryblok | TwoGridColumnCardStoryblok;

/**
 * Storyblok story object structure
 */
export interface StoryblokStory<T = StoryblokComponent> {
  /** Story ID */
  id: number;
  /** Story UUID */
  uuid: string;
  /** Story name */
  name: string;
  /** Story slug */
  slug: string;
  /** Full slug path */
  full_slug: string;
  /** Creation timestamp */
  created_at: string;
  /** Publication timestamp */
  published_at: string;
  /** First publication timestamp */
  first_published_at: string;
  /** Story content */
  content: T;
  /** Whether this is the start page */
  is_startpage: boolean;
  /** Parent story ID */
  parent_id: number | null;
  /** Story group ID */
  group_id: string;
  /** Story position */
  position: number;
  /** Story tags */
  tag_list: string[];
  /** Story language */
  lang: string;
  /** Story path */
  path: string;
  /** Alternative language versions */
  alternates: Array<{
    id: number;
    name: string;
    slug: string;
    published: boolean;
    full_slug: string;
    is_folder: boolean;
  }>;
  /** Translated slugs */
  translated_slugs: Array<{
    path: string;
    name: string;
    lang: string;
  }>;
}
