import React from 'react';
import { pdf, Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
	page: { padding: 24 },
	section: { marginBottom: 12 },
	title: { fontSize: 24, marginBottom: 12 },
	text: { fontSize: 12, lineHeight: 1.4 },
});

async function generateExamplePdfBlob(): Promise<Blob> {
	const doc = (
		<Document>
			<Page size="A4" style={styles.page}>
				<View style={styles.section}>
					<Text style={styles.title}>Example PDF</Text>
					<Text style={styles.text}>
						PDF generated by React in Astro.
					</Text>
				</View>
				<View style={styles.section}>
					<Text style={styles.text}>• Item 1</Text>
					<Text style={styles.text}>• Item 2</Text>
					<Text style={styles.text}>• Item 3</Text>
				</View>
			</Page>
		</Document>
	);

	const instance = pdf();
	instance.updateContainer(doc);
	return await instance.toBlob();
}

export default function DownloadPdfButton(): React.ReactElement {

	const handleClick = async () => {
		try {
			const blob = await generateExamplePdfBlob();
			const url = URL.createObjectURL(blob);
			try {
				const link = document.createElement('a');
				link.href = url;
				link.download = 'example.pdf';
				document.body.appendChild(link);
				link.click();
				link.remove();
			} finally {
				URL.revokeObjectURL(url);
			}
		} catch (error) {
			console.error('Failed to generate PDF', error);
		} 
	};

	return (
        <button onClick={handleClick} className="text-lg font-medium rounded-xl text-gray-500">
            Download PDF
        </button>
	);
}

